### ISSUE TITLE
Implement MPR

### ISSUE THREAD

**Issue by eagle49** [epam/med3web#10]
Hi
Thank you for your wonderful project.
I`m interested in MPR in this project and going to build individual project that only do the MPR with file or folder input.
Could you let me know some keyword such as which loader it is using or which files are for MPR?
Regards,

**Comment by VladislavShubnikov** [comment]
Thank you for the interest to our project.
Currently we are moving all our project to the ReactJS, and almost everything will be separated into "components" as a main ReactJS app basic stones. After completion this migration our project will receive a new look/design and new internal parts. It will be easy to extract only MPR rendering from the whole pipeline when our migration to ReactJS will be completed. Old (current published) version require a lot of engineering efforts to solve your task (separate some rendering functionality). Migration end is estimated in 1-2 monthes or so.

**Comment by eagle49** [comment]
Thank you for your update.
What we want to is to implement MPR in https://viewer.ohif.org/viewer/1.2.826.0.13854362241694438965858641723883466450351448 (OHIF viewer) by using this project.
In OHIF viewer it loads dcm files and convert to cornerstone json structure and draws on front-end.
To implement MPR in OHIF viewer, we need to extract the dcm files into json structure and convert it MPR volume data.
I can see that med3web uses threejs to display on front-end but I`m not sure how med3web implement MPR.
Could you let me know the only loading part and get MPR volumn data part in your project?
And Is it possible to integrate MPR in OHIF-viewer?

**Comment by dugiwarc** [comment]
Hello, @VladislavShubnikov 
Have you managed to migrate the project to ReactJS? If so would the repository be available to the public anytime soon?
