### ISSUE TITLE
how to pass jpeg 2000 dicom file format

### ISSUE THREAD

**Issue by MichleLI** [epam/med3web#12]
I hope to display 3d model of jpeg lossless or lossy

**Comment by VladislavShubnikov** [comment]
We are planning to support lossless and loss compressed formats reading in some future, may be two monthes or more.

**Comment by MichleLI** [comment]
Thank you for your reply!
I am going to work this job myself,so I would like to hear your advice about this.
I think only add jpeg2000 dicom file decode system.
What do you think ?

**Comment by MichleLI** [comment]
Thanks for you and your project!
I finished my job with your project
You saved my live.
Thank you again
