### ISSUE TITLE
Compressed image formats read is not supported

### ISSUE THREAD

**Issue by FedosZubi** [epam/med3web#21]
When I try to load compressed dcm files, I get the error message "Compressed image formats read is not supported" on the screen and "Wrong image pixels size. Readed 331506, but expected 913152" in the console. I think it's normal for now. Will support of the compressed dcm files be added in the future?

**Comment by VladislavShubnikov** [comment]
Some bug, connected with reading DCM files was just fixed. Error message with text "compression format" was not relevant to data. This issue is still under investigation.

**Comment by VladislavShubnikov** [comment]
now Med3Web supports several types of image compression:
- special JPEG lossless , etc compressed voxels
- entire *.dcm files can be packed into single *.gz file and open as a single file (not a lot of dcm files)
