### ISSUE TITLE
Usage of med3web as an external library

### ISSUE THREAD

**Issue by vdyma** [epam/med3web#54]
Hello! I'd like to integrate your tool as a package for datagrok.ai platform (https://github.com/datagrok-ai/public/issues/46), but if I understand correctly currently it is a standalone web app that cannot be used as an external library. Please, let me know how I can use med3web as an external library to read and view MRI files or if it's not currently possible, is it planned to make med3web to work as an external library?

**Comment by DanilRostov** [comment]
Hello @vdyma. Thank you for your question!
This feature haven't implemented yet, but we are looking for a solution to do this in the future releases.
If you are still interested in that, we can add you to waiting list and email, when it's done.

**Comment by skalkin** [comment]
@DanilRostov just wondering if you still plan to introduce this feature?

**Comment by Antonio-Riccelli** [comment]
I'd be interested as well.

**Comment by DanilRostov** [comment]
Hands on,

We are still working on this feature. 
Will let you know as soon as it implemented.
Thank you.
